#FROM registry.mckesson.com/devservices/mcklabs-node-dind-pipeline-base:0.0.1
FROM mck-developer-services-docker.jfrog.io/mcklabs-node-dind-pipeline-base:3.0.0
ARG GCP_KEY={"test":"test"}
ARG PULUMI_KEY
COPY . /source
WORKDIR /source
RUN mkdir gcp
RUN echo $GCP_KEY > ./gcp/gcpKey.json
ENV GCLOUD_KEYFILE_JSON ./gcp/gcpKey.json
RUN  cd .pipeline && chmod +x *.sh && cd ..
FROM pulumi/pulumi-base:2.16.2
COPY . /pulumi/projects
RUN echo $PULUMI_KEY
ENV PULUMI_KEY $PULUMI_KEY