name: DestroyState
on:
 workflow_dispatch:
  
 
jobs:
  destroyState:
    name: Pubsub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Change to Samples
      
        run: |
          cd sample
      - uses: pulumi/actions@v1
        with:
          command: destroy -s dev
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
          
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
